"""empty message

Revision ID: 5774a8b45dba
Revises: 61e2fa43da05
Create Date: 2017-05-01 14:32:37.883731

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5774a8b45dba'
down_revision = '61e2fa43da05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grants')
    op.drop_table('tokens')
    op.drop_table('clients')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('client_id', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('client_secret', sa.VARCHAR(length=55), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=400), autoincrement=False, nullable=True),
    sa.Column('is_confidential', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('_redirect_uris', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('_default_scopes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], [u'users.id'], name=u'clients_user_id_fkey'),
    sa.PrimaryKeyConstraint('client_id', name=u'clients_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('tokens',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('client_id', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('token_type', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('access_token', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('refresh_token', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('expires', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('_scopes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['client_id'], [u'clients.client_id'], name=u'tokens_client_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], [u'users.id'], name=u'tokens_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'tokens_pkey'),
    sa.UniqueConstraint('access_token', name=u'tokens_access_token_key'),
    sa.UniqueConstraint('refresh_token', name=u'tokens_refresh_token_key')
    )
    op.create_table('grants',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('client_id', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('redirect_uri', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('expires', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('_scopes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['client_id'], [u'clients.client_id'], name=u'grants_client_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], [u'users.id'], name=u'grants_user_id_fkey', ondelete=u'CASCADE'),
    sa.PrimaryKeyConstraint('id', name=u'grants_pkey')
    )
    # ### end Alembic commands ###
